IF OBJECT_ID(N'dbo.TaskAttachments', N'U') IS NOT NULL
  DROP TABLE dbo.TaskAttachments;
GO

IF OBJECT_ID(N'dbo.Tasks', N'U') IS NOT NULL
  DROP TABLE dbo.Tasks;
GO

CREATE TABLE dbo.Tasks (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  UserId NVARCHAR(128) NOT NULL,
  Title NVARCHAR(500) NOT NULL,
  Completed BIT NOT NULL CONSTRAINT DF_Tasks_Completed DEFAULT (0),
  DueDate DATE NULL,
  Category NVARCHAR(200) NULL,
  Color NVARCHAR(32) NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Tasks_CreatedAt DEFAULT (SYSUTCDATETIME()),
  UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Tasks_UpdatedAt DEFAULT (SYSUTCDATETIME())
);

CREATE INDEX IX_Tasks_UserId ON dbo.Tasks (UserId);

CREATE TABLE dbo.TaskAttachments (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  TaskId UNIQUEIDENTIFIER NOT NULL,
  UserId NVARCHAR(128) NOT NULL,
  BlobPath NVARCHAR(1024) NOT NULL,
  FileName NVARCHAR(500) NOT NULL,
  ContentType NVARCHAR(200) NULL,
  SizeBytes BIGINT NOT NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_TaskAttachments_CreatedAt DEFAULT (SYSUTCDATETIME()),
  CONSTRAINT FK_TaskAttachments_Tasks FOREIGN KEY (TaskId) REFERENCES dbo.Tasks (Id) ON DELETE CASCADE
);

CREATE INDEX IX_TaskAttachments_TaskId ON dbo.TaskAttachments (TaskId);
